config/routes.rb
Rails.application.routes.draw do
  # resources :books
  # root "books#index"
 require 'sidekiq/web'
 mount Sidekiq::Web => '/sidekiq'
  root 'projects#index'
  post "hello", to: 'projects#hello'
  resources :projects do
    collection do
      get 'search'
    end

  end
  # patch 'assign_developer', to: 'bugs#assign_developer'
  resources :bugs do
   member do
      patch :assign_developer
    end
  end

devise_for :users, controllers: {
  registrations: 'users/registrations',
  sessions: 'users/sessions',
  passwords: 'users/passwords',
  confirmations: 'users/confirmations',
  unlocks: 'users/unlocks'
}


end

app/models/project.rb
class Project < ApplicationRecord
  # belongs_to :manager, class_name: 'User', foreign_key: 'manager_id'
  # belongs_to :qa, class_name: 'User', optional: true
  # has_many :bugs, dependent: :destroy

  belongs_to :manager, class_name: 'User', foreign_key: 'manager_id'
  has_many :project_assignments , dependent: :destroy
  has_many :user , through: :project_assignments
  has_many :qas, -> { where(project_assignments: { role: 'qa' }) }, through: :project_assignments, source: :user
    accepts_nested_attributes_for :project_assignments
    has_many :bug , dependent: :destroy

validates :title, presence: true
  validates :description, presence: true, length: { minimum: 10 }

	
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  include ProjectNotifier
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    if current_user.manager?
      @projects = current_user.managed_projects
    else
      @projects = current_user.projects
  end
  end
  def search
    @projects = if params[:query].present?
                  Project.where('title LIKE ?', "%#{params[:query]}%")
                else
                  Project.all
                end
    render :index
  end
 
  def show
    @project = Project.find(params[:id])
    @bugs = Bug.where(project_id: @project.id)
  end

  def new
    @project = Project.new
    @project.project_assignments.build

  end
    def hello
      # puts  'Hellow'
     HelloJob.perform_at(10.seconds.from_now)
    end
  def create
    @project = Project.new(project_params)
    @project.manager_id = current_user.id


    if @project.save
            update_project_assignments

      redirect_to @project, notice: 'Project was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])

    if @project.update(project_params)
       update_project_assignments
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
  @project = Project.find(params[:id])
  @project.destroy
  redirect_to root_path, notice: 'Project was successfully destroyed.'
end  
# def destroy_pr
#   # @project = Project.find(params[:id])
#   @project.destroy
#   redirect_to root_path, notice: 'Project was successfully destroyed.'
# end

   def update_project_assignments
    existing_qa_ids = @project.user.where(role: 'qa').pluck(:id)
    selected_qa_ids = params[:project][:user_ids].map(&:to_i)
    removed_qa_ids = existing_qa_ids - selected_qa_ids

    @project.project_assignments.where(user_id: removed_qa_ids).destroy_all

    # Add project assignments for selected QAs
    selected_qa_ids.each do |qa_id|
      @project.project_assignments.find_or_create_by(user_id: qa_id)
    end
  end

  private

  def project_params
    params.require(:project).permit(:title, :description, :manager_id,qa_ids: [])
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with model: @project do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
      <% @project.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
      <% @project.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

    <%# <div> %>
  
   <div>
    <%= form.label :qas, 'Select QAs' %><br>
    <% User.where(role: ['qa', 'developer']).each do |qa| %>
      <% checked = @project.user.exists?(qa.id) %>
      <%= check_box_tag 'project[user_ids][]', qa.id, checked %>
      <%= label_tag "project_user_ids_#{qa.id}", qa.email %><br>
    <% end %>
  </div>
   
   <%#  <%= form.label :user_ids, 'Select Users' %><br>
   <%#   <%= form.collection_select :user_ids, User.where(role: 'qa'), :id, :email, {}, { multiple: true } %>

  <%# </div> %>

  


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Edit</h1>
<%= render "form", project: @project %>

app/views/projects/index.html.erb
<div class="container">
  <div class="card">
  
<div class="card-header">
  <%= form_with url: search_projects_path, method: :get, local: true do %>
 <div class="d-flex flex-row">
  
   <%= text_field_tag :query, params[:query], class: 'form-control' , placeholder: "Search Project"%>
    <%= submit_tag 'Search', class: 'btn btn-primary ml-2' %>
 </div>
 
 <% end %>

</div>

<div class="card-body">
  
<h2>Search Results</h2>
<div class="container">
  <% if @projects.any? %>
  
 
  

      <table border="1">
        <tr>
          <th class="p-2">ID</th>
          <th class="p-2">Title</th>
          <th class="p-2">Description</th>
          <th class="p-2">Action</th>
        </tr>
          <% @projects.each do |project| %>
        <tr>
          <td class="p-2">
            <%= project.id%>
          </td> 
           <td class="p-2">
            <%= project.title%>
          </td> 
           <td class="p-2">
            <%= project.description%>
          </td> 
           <td>
             <table class="nested-table">
                    <tr class="p-2">
                        <td >
      <%= link_to "Show", project_path(project) , class: 'btn btn-info'%>
    </td>  
                        <td >    <%= link_to " Edit" , edit_project_path(project), class: 'btn btn-warning' %></td>
                    
                        <td>   <%= button_to "Destroy ", project, method: :delete , class: 'btn btn-danger'%></td>
                    </tr>
                </table>
           
          </td> 
        </tr>
     

      <%# <li><%= link_to project.title, project_path(project) %>
      <%# </li> %>
    <% end %>
  </table>
<% else %>
  <p>No projects found</p>
<% end %>
</div>




<%if current_user.manager?%>





<%= link_to "New Project", new_project_path , class: 'btn btn-success my-4'%>

<%end%>
</div>
</div>
</div>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project%>

app/views/projects/show.html.erb
<h1><%=@project.title%></h1>
<p><%=@project.description%></p>

<% if current_user.manager? %>
<h3>Assigned Users</h3>
<p>
	<%@project.user.each do |usr|%>
	<li><%= usr.email%></li>
	<%end%>

	<p> <%= link_to "Edit", edit_project_path(@project)%></p>
<p>


  <%= button_to "Delete ", @project, method: :delete %>

</p>

</p>




<%end%>
<% if @bugs.empty?%>
<%else%>
<h3>Bug Found!</h3>

<p> <% @bugs.each do |bug|%>
	<div>
Status: <%=  bug.status.humanize %><br>
		Title: <%= link_to bug.title, bug %><br>Description: <%= bug.body %> <br> Created by: <%= bug.qa.email %>  

		
	</div>	<hr/>
	<%end%>
</p>	

<%end%>



<%# <%= link_to "Create new bug", new_bug_path%>
<% if current_user.qa?%>
<%= link_to "Create new bug", new_bug_path(project_id: @project.id) %>
<%end%>

<p><%= link_to "Go back to home", root_url%></p>