config/routes.rb
Rails.application.routes.draw do
  # resources :books
  # root "books#index"
 require 'sidekiq/web'
 mount Sidekiq::Web => '/sidekiq'
  root 'projects#index'
  post "hello", to: 'projects#hello'
  resources :projects do
    collection do
      get 'search'
    end

  end
  # patch 'assign_developer', to: 'bugs#assign_developer'
  resources :bugs do
   member do
      patch :assign_developer
    end
  end

devise_for :users, controllers: {
  registrations: 'users/registrations',
  sessions: 'users/sessions',
  passwords: 'users/passwords',
  confirmations: 'users/confirmations',
  unlocks: 'users/unlocks'
}


end

app/models/bug.rb
class Bug < ApplicationRecord

  enum bug_type: {bug: 0, feature: 1}
 enum status: [:new_bug, :started, :completed, ]

  belongs_to :project   # Assuming bugs belong to a project (you may need to adjust this association)

  belongs_to :qa, class_name: 'User', foreign_key: 'qa_id'
  belongs_to :developer, class_name: 'User', foreign_key: 'developer_id' , optional: true
  has_one_attached :image
  validates :title, presence: true, uniqueness: true
  validates :status, presence: true
  validates :bug_type, presence: true


end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @bugs = current_user.bugs_assigned
  end

  def show
    @bug = Bug.find(params[:id])
  end

  def new
    @bug = Bug.new
    @projects = current_user.projects if current_user.qa?
    @project = Project.find(params[:project_id]) if params[:project_id]

    @developers = User.developer.all
  end

  def create 
  @bug = Bug.new(bug_params)
  @bug.qa = current_user if current_user.qa?

  if @bug.save
    redirect_to @bug, notice: 'Bug was successfully created.'
  else
        puts @bug.errors.full_messages  # Print errors to console for debugging

    render :new, status: :unprocessable_entity
  end
end

  def edit
    @bug = Bug.find(params[:id])
  end

  def update
    @bug = Bug.find(params[:id])

    if @bug.update(bug_params)
      redirect_to @bug, notice: 'Bug was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end
  def update_status
    @bug = Bug.find(params[:id])
    new_status = params[:status].to_sym  # Convert status to symbol

    if @bug.update(status: new_status)
      render json: { message: 'Bug status updated successfully' }
    else
      render json: { error: @bug.errors.full_messages.join(', ') }, status: :unprocessable_entity
    end
  end
def assign_developer
    byebug
  @bug = Bug.find(params[:id]) # Use :id to fetch the bug record
  
  if @bug.update(developer_id: current_user.id)
    redirect_to @bug, notice: 'You have been assigned to this bug.'
  else
    redirect_to @bug, alert: 'Unable to assign yourself to this bug.'
  end
end


  # def destroy
  #   @bug = Bug.find(params[:id])
  #   @bug.destroy

  #   redirect_to bugs_url, notice: 'Bug was successfully destroyed.'
  # end
  def destroy
  @bug = Bug.find(params[:id])
  if @bug.destroy
    redirect_to bugs_url, notice: 'Bug was successfully destroyed.'
  else
    Rails.logger.debug { "Failed to destroy bug: #{@bug.errors.full_messages.join(', ')}" }
    redirect_to bugs_url, alert: 'Failed to destroy bug.'
  end
end

  private

  def bug_params
    params.require(:bug).permit(:title, :body, :project_id, :developer_id, :image,:status)
  end
end

app/helpers/bugs_helper.rb
module BugsHelper
end

app/views/bugs/_form.html.erb
<%= form_with model: @bug do |form| %>
  <div>
    <%= form.label :type %><br>
    <%= form.select :bug_type, Bug.bug_types.keys.map { |t| [t.humanize, t] } %>
  </div>
   <div class="field">
    <%= form.label :status %><br>
    <%= form.select :status, Bug.statuses.keys.map { |status| [status.humanize, status] }, { include_blank: false } %>
  </div>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
      <% @bug.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <%= form.hidden_field :project_id, value: @project.id if @project %>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
      <% @bug.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
    <div>
    <%= form.label :image, 'Upload Image(.png or .gif only)' %> <br>
    <%= form.file_field :image, accept: 'image/png,image/gif' %>
    <% @bug.errors.full_messages_for(:image).each do |message| %>
      <div><%= message %></div>
          <% end %>

  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

  <%#
<% if !current_user.developer? %>
  <%# <div>
    <%= form.label :developer_id, 'Assign Developer' %><br>
 <%#   <% User.developer.map do |developer| %>
 <%#     <%= form.radio_button :developer_id, developer.id %>
 <%#     <%= form.label "developer_#{developer.id}", developer.email %><br>
 <%#   <% end %>
  <%#</div>
<%end%>
  
  


  

app/views/bugs/edit.html.erb
<h1>Edit</h1>
<%= render "form", bug: @bug %>
<p><%= link_to "Go back to home", root_url%></p>

app/views/bugs/index.html.erb
<h1>Available Bugs</h1>
<ul>
	<% @bugs.each do |bug| %>
	<li>
		<%= link_to bug.title , bug%>
	</li>
	<%end%>
</ul>
	

<% if !current_user.developer? %>
<%= link_to "Create New Bug", new_bug_path %>
<%else%>
<p> No Bugs Available!</p>
<%end%>

app/views/bugs/new.html.erb
<h1>New Bug</h1>

<%= render 'form', bug: @bug%>

app/views/bugs/show.html.erb
<h1><%=@bug.title%></h1>


<p><%=@bug.body%></p>
<% if @bug.image.attached? %>
	  <%= image_tag url_for(@bug.image) , width: 200, height: 200%>

<%end%>


<p> <%= link_to "Edit", edit_bug_path(@bug)%></p>
<% if !current_user.developer? %>
<p>

  <%= button_to "Delete ", @project, method: :delete %>

</p>
<%end%>

<% if current_user.developer? %>
<% if @bug.developer_id.nil? %>
<%# <%= link_to 'Assign to me', assign_developer_bug_path(@bug), method: :patch, class: 'btn btn-primary', data: { confirm: 'Are you sure you want to assign this bug to yourself?' } %> %>

<%= button_to "Assign to me" , assign_developer_bug_path , method: :patch, class: 'btn btn-primary'%>

<%else%>
<<p>Assigned to: <%= @bug.developer.email%></p> 

<%end%>


<%end%>

<%= form_for @bug, url: bug_path(@bug), method: :patch do |f| %>
  <div class="form-group w-25">
    <%= f.label :status, "Change Status:" %>
    <%= f.select :status, Bug.statuses.keys.map { |status| [status.humanize, status] }, {}, class: 'form-control' %>
  </div>
  <%= f.submit "Update Status", class: 'btn btn-primary btn-sm' %>
<% end %>
<p><%= link_to "Go back to home", root_url%></p>